[tool.poetry]
name = "001"
version = "0.1.0"
description = ""
authors = ["bamjun <khy5116@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
moviepy = "^1.0.3"
Pillow = ">=9.0,<10.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
